# Generated by Django 5.0.4 on 2024-04-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_add_recipe_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_recipe_model',
            old_name='recipe_type',
            new_name='recipe_category',
        ),
    ]
