# Generated by Django 5.0.4 on 2024-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_rename_recipe_type_add_recipe_model_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_recipe_model',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
