# Generated by Django 5.0.4 on 2024-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0004_add_recipe_model_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='user_image',
            field=models.ImageField(null=True, upload_to='static/user_img'),
        ),
    ]
