# Generated by Django 5.0.4 on 2024-04-29 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0005_custom_user_display_name_custom_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='chef_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100, null=True)),
                ('skill', models.CharField(max_length=100, null=True)),
                ('resume_latter', models.CharField(max_length=100, null=True)),
                ('profile_img', models.ImageField(null=True, upload_to='static/profile_img')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='viewer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100, null=True)),
                ('profile_img', models.ImageField(null=True, upload_to='static/profile_img')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
